export enum CheckboxLabels {
  Home = "home",
  Desktop = "desktop",
  Notes = "notes",
  Commands = "commands",
  Documents = "documents",
  Workspace = "workspace",
  Downloads = "downloads",
  WordFile = "wordFile",
  ExcelFile = "excelFile",
  React = "react",
  Angular = "angular",
  Veu = "veu",
  Office = "office",
  Public = "public",
  Private = "private",
  Classified = "classified",
  General = "general",
}
