export const sidebarItems = {
  elements: [
    "Text Box",
    "Check Box",
    "Radio Button",
    "Web Tables",
    "Buttons",
    "Links",
    "Broken Links - Images",
    "Upload and Download",
    "Dynamic Properties",
  ],
  forms: ["Practice Form"],
  alerts: [
    "Browser Windows",
    "Alerts",
    "Frames",
    "Nested Frames",
    "Modal Dialogs",
  ],
  widgets: [
    "Accordian",
    "Auto Complete",
    "Date Picker",
    "Slider",
    "Progress Bar",
    "Tabs",
    "Tool Tips",
    "Menu",
    "Select Menu",
  ],
  interactions: [
    "Sortable",
    "Selectable",
    "Resizable",
    "Droppable",
    "Dragabble",
  ],
  bookStoreApplication: ["Login", "Book Store", "Profile", "Book Store API"],
};
